# Site settings
title: nomcha
#email: tasty@nomcha.com
description: > # this means to ignore newlines until "baseurl:"
   a concise blog of tasty teas.

baseurl: "/nomcha" # the subpath of your site, e.g. /blog/

timezone: America/Chicago
encoding: utf-8

gems:
     - jekyll-sitemap

exclude: [TODO.txt, Gemfile*]
permalink:
   /:categories/:title/
     
# Build settings
markdown: redcarpet
