# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/nomcha" # the subpath of your site, e.g. /blog/
twitter_username: jekyllrb
github_username:  jekyll

timezone: America/Chicago
encoding: utf-8

gems:
     - jekyll-sitemap

exclude: [TODO.txt, Gemfile*]
permalink:
   /:categories/:title/
     
# Build settings
markdown: redcarpet
